# Client Dockerfile
FROM node:14-slim

WORKDIR /home/node/client

COPY ./package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

ENV PREACT_APP_BASE_URL=http://localhost:5001/api

CMD ["npm", "run", "start"]