version: "3.7"
services:
  client:
    environment:
      - NODE_ENV=development
      - PORT=5000
    build:
      dockerfile: Dockerfile.dev
      context: ./
    working_dir: /home/node/client
    stdin_open: true
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/home/node/client
      - /home/node/client/node_modules
