# First stage
FROM node:14-slim as builder

WORKDIR /home/node/client

COPY ./package*.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV PREACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

# Copy into second Caddy stage
FROM caddy:2.4.6-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /home/node/client/build/ /srv

EXPOSE 80

EXPOSE 443